homebrew_installed_packages:
  - antibody
  - composer
  - gnupg
  - htop
  - mobile-shell
  - {name: mpv, install_options: 'with-bundle'}
  - pass
  - php71
  - pinentry-mac
  - yarn

homebrew_taps:
  - getantibody/tap
  - homebrew/php
  - caskroom/cask

homebrew_cask_apps:
  - alfred
  - atext
  - flux
  - google-chrome
  - harvest
  - iterm2
  - jotta
  - osxfuse
  - postman
  - sequel-pro
  - slack
  - spectacle
  - spotify
  - transmission
  - typora
  - virtualbox
  - visual-studio-code

homebrew_upgrade_all_packages: yes

mas_email: "torrottum@gmail.com"
mas_signin_dialog: yes
mas_installed_apps:
  - { id: 926036361, name: "LastPass: Password Manager and Secure Vault" }
  - { id: 531349534, name: "Tadam: Stay focused at work" }

computer_name: Zeus
timezone: Europe/Oslo

finder_default_path: "file://{{ ansible_env.HOME }}/"
