homebrew_installed_packages:
  - antibody
  - composer
  - gnupg
  - htop
  - mobile-shell
  - {name: mpv, install_options: 'with-bundle'}
  - pass
  - php71
  - pinentry-mac
  - pwgen
  - yarn

homebrew_taps:
  - getantibody/tap
  - homebrew/php
  - caskroom/cask

homebrew_cask_apps:
  - alfred
  - atext
  - flux
  - google-chrome
  - harvest
  - iterm2
  - jotta
  - osxfuse
  - postman
  - sequel-pro
  - sketch
  - slack
  - spectacle
  - spotify
  - torbrowser
  - transmission
  - virtualbox
  - visual-studio-code

homebrew_upgrade_all_packages: yes

hostname: Zeus
username: tor
timezone: Europe/Oslo

finder_default_path: "file://{{ ansible_env.HOME }}/"

wallpaper_url: https://images.unsplash.com/photo-1502582877126-512f3c5b0a64?ixlib=rb-0.3.5&q=85&fm=jpg&crop=entropy&cs=srgb&dl=casey-horner-339165.jpg&s=ad416e5df5da678c17183d00411ffe8d
