---
- hosts: all
  connection: local

  vars_files:
    - config.yml

  roles:
    - role: geerlingguy.homebrew
      tags: ['brew', 'apps']

  tasks:
    - include: tasks/sshfs.yml
      tags: ['brew', 'apps']
