---
- hosts: all
  connection: local

  vars_files:
    - config.yml

  roles:
    - role: geerlingguy.homebrew
      tags: ['brew', 'apps']

    - role: geerlingguy.mas
      tags: ['mas', 'apps']

  tasks:
    - include: tasks/sshfs.yml
      tags: ['brew', 'apps']

    - include: tasks/macos.yml
      tags: ['macos', 'settings']

    - include: tasks/wallpaper.yml
      tags: ['wallpaper', 'settings']
