# Based off ~/.macos — https://mths.be/macos
# Customized for my needs

---
- name: Close any open System Preferences panes
  command: osascript -e 'tell application "System Preferences" to quit'

- name: Set computer name
  command: "{{ item }}"
  become: true
  with_items:
    - 'scutil --set ComputerName "{{ computer_name }}"'
    - 'scutil --set HostName "{{ computer_name }}"'
    - 'scutil --set LocalHostName "{{ computer_name }}"'
    - 'defaults write /Library/Preferences/SystemConfiguration/com.apple.smb.server NetBIOSName -string "{{ computer_name }}"'

- name: Set the timezone
  command: systemsetup -settimezone "{{ timezone }}" > /dev/null
  become: true

- name: Disable the sound effects on boot
  command: nvram SystemAudioVolume=" "
  become: true

- name: Expand save and print panels by default
  osx_defaults: host="{{ item.host | default('') }}" domain="{{ item.domain }}" key="{{ item.key }}" type="{{ item.type }}" value="{{ item.value }}" state=present
  with_items:
    - {domain: NSGlobalDomain, key: NSNavPanelExpandedStateForSaveMode, type: bool, value: true}
    - {domain: NSGlobalDomain, key: NSNavPanelExpandedStateForSaveMode2, type: bool, value: true}
    - {domain: NSGlobalDomain, key: PMPrintingExpandedStateForPrint, type: bool, value: true}
    - {domain: NSGlobalDomain, key: PMPrintingExpandedStateForPrint2, type: bool, value: true}

- name: Save to disk (not iCloud by default)
  osx_defaults: domain=NSGlobalDomain key=NSDocumentSaveNewDocumentsToCloud type=bool value=false state=present

- name: Automatically quit printer app once the print jobs complete
  osx_defaults: domain=com.apple.print.PrintingPrefs key="Quit When Finished" type=bool value=true state=present

- name: Disable the “Are you sure you want to open this application?” dialog
  osx_defaults: domain=com.apple.LaunchServices key=LSQuarantine type=bool value=false state=present

- name: Remove duplicates in the “Open With” menu
  command: /System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -kill -r -domain local -domain system -domain user

- name: Disable automatic termination of inactive apps
  osx_defaults: domain=NSGlobalDomain key=NSDisableAutomaticTermination type=bool value=true state=present

- name: Disable annoying text features (capitalization, smart dashes and quotes, period substitution, auto-correct)
  osx_defaults: host="{{ item.host | default('') }}" domain="{{ item.domain }}" key="{{ item.key }}" type="{{ item.type }}" value="{{ item.value }}" state=present
  with_items:
    - {domain: NSGlobalDomain, key: NSAutomaticCapitalizationEnabled, type: bool, value: false}
    - {domain: NSGlobalDomain, key: NSAutomaticDashSubstitutionEnabled, type: bool, value: false}
    - {domain: NSGlobalDomain, key: NSAutomaticPeriodSubstitutionEnabled, type: bool, value: false}
    - {domain: NSGlobalDomain, key: NSAutomaticQuoteSubstitutionEnabled, type: bool, value: false}
    - {domain: NSGlobalDomain, key: NSAutomaticSpellingCorrectionEnabled, type: bool, value: false}

- name: Disable annoying text features (capitalization, smart dashes and quotes, period substitution, auto-correct)
  osx_defaults: host="{{ item.host | default('') }}" domain="{{ item.domain }}" key="{{ item.key }}" type="{{ item.type }}" value="{{ item.value }}" state=present
  with_items:
    - {domain: NSGlobalDomain, key: NSAutomaticCapitalizationEnabled, type: bool, value: false}
    - {domain: NSGlobalDomain, key: NSAutomaticDashSubstitutionEnabled, type: bool, value: false}
    - {domain: NSGlobalDomain, key: NSAutomaticPeriodSubstitutionEnabled, type: bool, value: false}
    - {domain: NSGlobalDomain, key: NSAutomaticQuoteSubstitutionEnabled, type: bool, value: false}
    - {domain: NSGlobalDomain, key: NSAutomaticSpellingCorrectionEnabled, type: bool, value: false}

- name: "Trackpad: enable tap to click for this user and for the login screen"
  osx_defaults: host="{{ item.host | default('') }}" domain="{{ item.domain }}" key="{{ item.key }}" type="{{ item.type }}" value="{{ item.value }}" state=present
  with_items:
    - {domain: com.apple.driver.AppleBluetoothMultitouch.trackpad , key: Clicking, type: int, value: 1}
    - {host: 'currentHost', domain: NSGlobalDomain, key: com.apple.mouse.tapBehavior, type: int, value: 1}
    - {domain: NSGlobalDomain, key: com.apple.mouse.tapBehavior, type: int, value: 1}

- name: Increase sound quality for Bluetooth headphones/headsets
  osx_defaults: domain=com.apple.BluetoothAudioAgent key="Apple Bitpool Min (editable)" type=int value=40 state=present

- name: Enable full keyboard access for all controls
  osx_defaults: domain=NSGlobalDomain key=AppleKeyboardUIMode type=int value=3 state=present

- name: Disable press-and-hold for keys in favor of key repeat and set key repeat rate
  osx_defaults: host="{{ item.host | default('') }}" domain="{{ item.domain }}" key="{{ item.key }}" type="{{ item.type }}" value="{{ item.value }}" state=present
  with_items:
    - {domain: NSGlobalDomain, key: ApplePressAndHoldEnabled, type: bool, value: false}
    - {domain: NSGlobalDomain, key: KeyRepeat, type: float, value: 1}
    - {domain: NSGlobalDomain, key: InitialKeyRepeat, type: int, value: 10}


- name: Stop iTunes from responding to the keyboard media keys
  command: launchctl unload -w /System/Library/LaunchAgents/com.apple.rcd.plist 2> /dev/null

- name: Require password immediately after sleep or screen saver begins
  osx_defaults: host="{{ item.host | default('') }}" domain="{{ item.domain }}" key="{{ item.key }}" type="{{ item.type }}" value="{{ item.value }}" state=present
  with_items:
    - {domain: com.apple.screensaver, key: askForPassword, type: int, value: 1}
    - {domain: com.apple.screensaver, key: askForPasswordDelay, type: float, value: 0}


- name: Set the default location for new Finder windows
  osx_defaults: host="{{ item.host | default('') }}" domain="{{ item.domain }}" key="{{ item.key }}" type="{{ item.type }}" value="{{ item.value }}" state=present
  with_items:
    - {domain: com.apple.finder, key: NewWindowTarget, type: string, value: PfLe}
    - {domain: com.apple.finder, key: askForPasswordDelay, type: string, value: "{{ finder_default_path }}"}

- name: "Finder: show all filename extensions"
  osx_defaults: domain=NSGlobalDOmain key=AppleShowAllExtensions type=bool value=true state=present

- name: Keep folders on top when sorting by name
  osx_defaults: domain=com.apple.finder key=_FXSortFoldersFirst type=bool value=true state=present

- name: When performing a search, search the current folder by default
  osx_defaults: domain=com.apple.finder key=FXDefaultSearchScope type=string value=SCcf state=present

- name: Disable the warning when changing a file extension
  osx_defaults: domain=com.apple.finder key=FXEnableExtensionChangeWarning type=bool value=false state=present

- name: Avoid creating .DS_Store files on network or USB volumes
  osx_defaults: host="{{ item.host | default('') }}" domain="{{ item.domain }}" key="{{ item.key }}" type="{{ item.type }}" value="{{ item.value }}" state=present
  with_items:
    - {domain: com.apple.desktopservices, key: DSDontWriteNetworkStores, type: bool, value: true}
    - {domain: com.apple.desktopservices, key: DSDontWriteUSBStores, type: bool, value: true}

- name: Disable disk image verification
  osx_defaults: host="{{ item.host | default('') }}" domain="{{ item.domain }}" key="{{ item.key }}" type="{{ item.type }}" value="{{ item.value }}" state=present
  with_items:
    - {domain: com.apple.frameworks.diskimages, key: skip-verify, type: bool, value: true}
    - {domain: com.apple.frameworks.diskimages, key: skip-verify-locked, type: bool, value: true}
    - {domain: com.apple.frameworks.diskimages, key: skip-verify-remote, type: bool, value: true}

- name: Automatically open a new Finder window when a volume is mounted
  osx_defaults: host="{{ item.host | default('') }}" domain="{{ item.domain }}" key="{{ item.key }}" type="{{ item.type }}" value="{{ item.value }}" state=present
  with_items:
    - {domain: com.apple.frameworks.diskimages, key: auto-open-ro-root, type: bool, value: true}
    - {domain: com.apple.frameworks.diskimages, key: auto-open-rw-root, type: bool, value: true}
    - {domain: com.apple.finder, key: OpenWindowForNewRemovableDisk, type: bool, value: true}

- name: Use list view in all Finder windows by default
  osx_defaults: domain=com.apple.finder key=FXPreferredViewStyle type=string value=Nlsv state=present

- name: Update settings
  osx_defaults: host="{{ item.host | default('') }}" domain="{{ item.domain }}" key="{{ item.key }}" type="{{ item.type }}" value="{{ item.value }}" state=present
  with_items:
    - {domain: com.apple.SoftwareUpdate, key: AutomaticCheckEnabled, type: bool, value: true}
    - {domain: com.apple.SoftwareUpdate, key: ScheduleFrequency, type: int, value: 1}
    - {domain: com.apple.SoftwareUpdate, key: AutomaticDownload, type: int, value: 1}
    - {domain: com.apple.SoftwareUpdate, key: CriticalUpdateInstall, type: int, value: 1}
    - {domain: com.apple.commerce, key: AutoUpdate, type: bool, value: true}
    - {domain: com.apple.commerce, key: AutoUpdateRestartRequired, type: bool, value: true}
